import { Injectable } from '@angular/core';
import { ChatEmoji } from './chatEmoji';

@Injectable({
  providedIn: 'root'
})
export class EmojiserviceService {


  private EMOJIS_;

  get EMOJIS(): ChatEmoji[] {
    return this.EMOJIS_;
  }


  constructor() {
    this.EMOJIS_ = [
      new ChatEmoji('GRINNING FACE', '&#128512;'),
      new ChatEmoji('GRINNING FACE WITH SMILING EYES', '&#128513;'),
      new ChatEmoji('FACE WITH TEARS OF JOY', '&#128514;'),
      new ChatEmoji('ROLLING ON THE FLOOR LAUGHING', '&#129315;'),
      new ChatEmoji('SMILING FACE WITH OPEN MOUTH', '&#128515;'),
      new ChatEmoji('SMILING FACE WITH OPEN MOUTH AND SMILING EYES & smiling face with open mouth & smiling eyes', '&#128516;'),
      new ChatEmoji('SMILING FACE WITH OPEN MOUTH AND COLD SWEAT & smiling face with open mouth & cold sweat', '&#128517;'),
      new ChatEmoji('SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES & smiling face with open mouth & closed eyes', '&#128518;'),
      new ChatEmoji('WINKING FACE', '&#128521;'),
      new ChatEmoji('SMILING FACE WITH SMILING EYES', '&#128522;'),
      new ChatEmoji('FACE SAVOURING DELICIOUS FOOD', '&#128523;'),
      new ChatEmoji('SMILING FACE WITH SUNGLASSES', '&#128526;'),
      new ChatEmoji('SMILING FACE WITH HEART-SHAPED EYES & smiling face with heart-eyes', '&#128525;'),
      new ChatEmoji('FACE THROWING A KISS', '&#128536;'),
      new ChatEmoji('KISSING FACE', '&#128535;'),
      new ChatEmoji('KISSING FACE WITH SMILING EYES', '&#128537;'),
      new ChatEmoji('KISSING FACE WITH CLOSED EYES', '&#128538;'),
      new ChatEmoji('WHITE SMILING FACE & smiling face', '&#9786;'),
      new ChatEmoji('SLIGHTLY SMILING FACE', '&#128578;'),
      new ChatEmoji('HUGGING FACE', '&#129303;'),
      new ChatEmoji('THINKING FACE', '&#129300;'),
      new ChatEmoji('NEUTRAL FACE', '&#128528;'),
      new ChatEmoji('EXPRESSIONLESS FACE', '&#128529;'),
      new ChatEmoji('FACE WITHOUT MOUTH', '&#128566;'),
      new ChatEmoji('FACE WITH ROLLING EYES', '&#128580;'),
      new ChatEmoji('SMIRKING FACE', '&#128527;'),
      new ChatEmoji('PERSEVERING FACE', '&#128547;'),
      new ChatEmoji('DISAPPOINTED BUT RELIEVED FACE', '&#128549;'),
      new ChatEmoji('FACE WITH OPEN MOUTH', '&#128558;'),
      new ChatEmoji('ZIPPER-MOUTH FACE', '&#129296;'),
      new ChatEmoji('HUSHED FACE', '&#128559;'),
      new ChatEmoji('SLEEPY FACE', '&#128554;'),
      new ChatEmoji('TIRED FACE', '&#128555;'),
      new ChatEmoji('SLEEPING FACE', '&#128564;'),
      new ChatEmoji('RELIEVED FACE', '&#128524;'),
      new ChatEmoji('NERD FACE', '&#129299;'),
      new ChatEmoji('FACE WITH STUCK-OUT TONGUE', '&#128539;'),
      new ChatEmoji('FACE WITH STUCK-OUT TONGUE AND WINKING EYE & face with stuck-out tongue & winking eye', '&#128540;'),
      new ChatEmoji('FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES & face with stuck-out tongue & closed eyes', '&#128541;'),
      new ChatEmoji('DROOLING FACE', '&#129316;'),
      new ChatEmoji('UNAMUSED FACE', '&#128530;'),
      new ChatEmoji('FACE WITH COLD SWEAT', '&#128531;'),
      new ChatEmoji('PENSIVE FACE', '&#128532;'),
      new ChatEmoji('CONFUSED FACE', '&#128533;'),
      new ChatEmoji('UPSIDE-DOWN FACE', '&#128579;'),
      new ChatEmoji('MONEY-MOUTH FACE', '&#129297;'),
      new ChatEmoji('ASTONISHED FACE', '&#128562;'),
      new ChatEmoji('WHITE FROWNING FACE & frowning face', '&#9785;'),
      new ChatEmoji('SLIGHTLY FROWNING FACE', '&#128577;'),
      new ChatEmoji('CONFOUNDED FACE', '&#128534;'),
      new ChatEmoji('DISAPPOINTED FACE', '&#128542;'),
      new ChatEmoji('WORRIED FACE', '&#128543;'),
      new ChatEmoji('FACE WITH LOOK OF TRIUMPH & face with steam from nose', '&#128548;'),
      new ChatEmoji('CRYING FACE', '&#128546;'),
      new ChatEmoji('LOUDLY CRYING FACE', '&#128557;'),
      new ChatEmoji('FROWNING FACE WITH OPEN MOUTH', '&#128550;'),
      new ChatEmoji('ANGUISHED FACE', '&#128551;'),
      new ChatEmoji('FEARFUL FACE', '&#128552;'),
      new ChatEmoji('WEARY FACE', '&#128553;'),
      new ChatEmoji('GRIMACING FACE', '&#128556;'),
      new ChatEmoji('FACE WITH OPEN MOUTH AND COLD SWEAT & face with open mouth & cold sweat', '&#128560;'),
      new ChatEmoji('FACE SCREAMING IN FEAR', '&#128561;'),
      new ChatEmoji('FLUSHED FACE', '&#128563;'),
      new ChatEmoji('DIZZY FACE', '&#128565;'),
      new ChatEmoji('POUTING FACE', '&#128545;'),
      new ChatEmoji('ANGRY FACE', '&#128544;'),
      new ChatEmoji('SMILING FACE WITH HALO', '&#128519;'),
      new ChatEmoji('FACE WITH COWBOY HAT & cowboy hat face', '&#129312;'),
      new ChatEmoji('CLOWN FACE', '&#129313;'),
      new ChatEmoji('LYING FACE', '&#129317;'),
      new ChatEmoji('FACE WITH MEDICAL MASK', '&#128567;'),
      new ChatEmoji('FACE WITH THERMOMETER', '&#129298;'),
      new ChatEmoji('FACE WITH HEAD-BANDAGE', '&#129301;'),
      new ChatEmoji('NAUSEATED FACE', '&#129314;'),
      new ChatEmoji('SNEEZING FACE', '&#129319;'),
      new ChatEmoji('SMILING FACE WITH HORNS', '&#128520;'),
      new ChatEmoji('IMP', '&#128127;'),
      new ChatEmoji('JAPANESE OGRE & ogre', '&#128121;'),
      new ChatEmoji('JAPANESE GOBLIN & goblin', '&#128122;'),
      new ChatEmoji('SKULL', '&#128128;'),
      new ChatEmoji('SKULL AND CROSSBONES', '&#9760;'),
      new ChatEmoji('GHOST', '&#128123;'),
      new ChatEmoji('EXTRATERRESTRIAL ALIEN & alien', '&#128125;'),
      new ChatEmoji('ALIEN MONSTER', '&#128126;'),
      new ChatEmoji('ROBOT FACE', '&#129302;'),
      new ChatEmoji('PILE OF POO', '&#128169;'),
      new ChatEmoji('SMILING CAT FACE WITH OPEN MOUTH', '&#128570;'),
      new ChatEmoji('GRINNING CAT FACE WITH SMILING EYES', '&#128568;'),
      new ChatEmoji('CAT FACE WITH TEARS OF JOY', '&#128569;'),
      new ChatEmoji('SMILING CAT FACE WITH HEART-SHAPED EYES & smiling cat face with heart-eyes', '&#128571;'),
      new ChatEmoji('CAT FACE WITH WRY SMILE', '&#128572;'),
      new ChatEmoji('KISSING CAT FACE WITH CLOSED EYES', '&#128573;'),
      new ChatEmoji('WEARY CAT FACE', '&#128576;'),
      new ChatEmoji('CRYING CAT FACE', '&#128575;'),
      new ChatEmoji('POUTING CAT FACE', '&#128574;'),
      new ChatEmoji('SEE-NO-EVIL MONKEY & see-no-evil', '&#128584;'),
      new ChatEmoji('HEAR-NO-EVIL MONKEY & hear-no-evil', '&#128585;'),
      new ChatEmoji('SPEAK-NO-EVIL MONKEY & speak-no-evil', '&#128586;'),
      new ChatEmoji('BOY', '&#128102;'),
      new ChatEmoji('boy, type-1-2', '&#128102;'),
      new ChatEmoji('boy, type-3', '&#128102;'),
      new ChatEmoji('boy, type-4', '&#128102;'),
      new ChatEmoji('boy, type-5', '&#128102;'),
      new ChatEmoji('boy, type-6', '&#128102;'),
      new ChatEmoji('GIRL', '&#128103;'),
      new ChatEmoji('girl, type-1-2', '&#128103;')];
  }

}
